name: START

on:
  repository_dispatch:
    types: [test_result]

jobs:
  default:
    # if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
          SECRET: ${{ secrets.TESTING }}
          EMPTY: ${{ secrets.EMPTY }}
        run: echo $SECRET $EMPTY
